### ISSUE TITLE
Two errors

### ISSUE THREAD

**Issue by chadbrewbaker** [taw/z3#3] opened 2016-11-07 18:59 UTC
Nice work! I was almost ready to wrap Z3 in Ruby bindings then found your project.

I got two errors when building.

Failures:

  1) Z3::FloatExpr to_s
     Failure/Error: expect(float_double.from_const(1234 * 0.5**1040).to_s).to eq("1.205078125B-1030")
     
       expected: "1.205078125B-1030"
            got: "0.00470733642578125B-1022"
     
       (compared using ==)
     # ./spec/float_expr_spec.rb:104:in `block (2 levels) in <module:Z3>'

  2) Regexp Crossword Solver experienced-5.txt matches output
     Failure/Error: expect(s).to match Regexp.new(/\A(?:#{rx})\z/)
     
       expected "TOBKH" to match /\A(?:[IT](O)*(BE|AD)*\1)\z/
       Diff:
       @@ -1,2 +1,2 @@
       -/\A(?:[IT](O)*(BE|AD)*\1)\z/
       +"TOBKH"
       
     # ./spec/integration/regexp_crossword_solver_spec.rb:23:in `block (5 levels) in <top (required)>'
     # ./spec/integration/regexp_crossword_solver_spec.rb:22:in `each'
     # ./spec/integration/regexp_crossword_solver_spec.rb:22:in `block (4 levels) in <top (required)>'

**Comment by taw** [comment] 2016-11-07 19:02
Which ruby version and platform is this?

**Comment by taw** [comment] 2016-11-07 19:09
CI for the project is at https://semaphoreci.com/taw/z3 with ruby 2.3.0 on Linux, and I run it locally on OSX, so these platforms are fine at least.

**Comment by chadbrewbaker** [comment] 2016-11-07 19:20
ruby 2.0.0p648 on OSX Sierra.  I'll have to play around to see what is different.

**Comment by taw** [comment] 2016-11-07 19:33
2.0.0 is officially past its end of life. Then again, I just tried it with 2.0.0-p648 from rbenv on OSX Yosemite and it all worked perfectly.

```
$ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin14.5.0]
$ bundle exec rspec
.............................................................................................................................................................................................................................

Finished in 23.4 seconds (files took 0.47924 seconds to load)
221 examples, 0 failures
```

**Comment by chadbrewbaker** [comment] 2016-11-07 19:35
Probably a deprecated gem I have then then.

**Comment by taw** [comment] 2016-11-07 22:40
If you can identify list of gems and z3 library version, I might be able to do something about it.

The way it is now, I'd need to close this as impossible to reproduce.

**Comment by taw** [comment] 2016-11-13 09:14
It's possible it's caused by unversioned gem dependencies, and that `z3` should specify minimum versions, but closing as unreproducible.

**Closed by taw** 2016-11-13 09:14 UTC
